### ISSUE TITLE
V1 Driver crash

### ISSUE THREAD

**Issue by rm37** [mswlogo/V1Driver-Bugs#32]
The V1 has been in my car(s) for 10 years now, and V1 Driver is a most welcome addition.  The V1Driver app recently started crashing approaching the same K band stationary radar set up on a road construction site.  There are multiple stationary  K band radar guns along this stretch of road, however, the app crashes only on the one site.  This radar site is third in order when northbound, obviously near last southbound, but the direction of approach does not matter.  These radar guns were encountered several times before V1 Driver started crashing at the one site. This particular gun gives the maximum signal to the V1 however, full strength Kband has been encountered by passing police cars without a failure.  Note my V1 Driver is up to date.

On a different note, I have a request.   The V1 Driver needs a larger indicator that the V1 is connected to V1 Driver, along with a warning tone/ sign if V1 loses connection. I use the dark mode most of the time with the V1 high and relatively hidden. In removing my V1 from the car during  the hot Texas summer, the power connection has lost it's securing clip.  Since the power cable is "buried" and to the fuse box, I have not wanted to replace the cable since the clip tends to break again quickly. Even with a new power cable, a larger confirmation of connection would be nice.  thanks, robert

**Comment by mswlogo** [comment]
Thanks for posting the bug and suggestion. Probably should be 2 bugs.

Anyway. First things first. Which flavor Android or iOS?

In either case under Debug Settings, send me a Log as soon as you can after the App Crashes.
On iOS the log needs to be turned on first.

Wait. I just checked the crash logs from apple and there is a crash report that is probably from you. Working on a fix now. Stay tuned.

**Comment by mswlogo** [comment]
I believe I have the crash fixed. If you want to join beta to test, send a log to me via the app.
You'll have to enable logging to send the log.

I just released Voice Disconnect option on Android today. iOS is next.

**Comment by rm37** [comment]
Thanks for the info, just sent the log to you.  Beta would be good.  My disconnect request, may I add, also comes from the fact  v1 and bt share the same spot when indicating online sometimes, so when V1 drops bt replaces but the word online is still present which Has fooled me a couple of times.

The V1 in dark mode and hidden, it is not obvious the V1 is now offline, which was an issue before V1Driver as well.


Thanks again for the follow up    rm


________________________________

**Comment by mswlogo** [comment]
I didn’t see any log. Are you sure it went out? You can just send me an email at drive@v1driver.com so I can get you on beta. I’m 99% sure it’s fixed in beta. 

I understand what you mean about v1 vs bt online. But you really should fix that connector regardless. Just crimp a new end on.

**Comment by rm37** [comment]
Hello, apparently my log didn't send.  My V1Driver is on a dedicated old iPhone 6 which is not connected to cell service hence no email.   I thought I could hotspot the email via my current phone. Will see if the phone will send using wifi.     crimping.....    thanks rm

**Comment by mswlogo** [comment]
No response.

**Comment by rm37** [comment]
Hello,

Just open this email, I'm not sure what this means. Maybe a reply to the email 2 years ago?

If so, I will attempt to link that iPhone which I still use to my email.  Am I still on the beta?

The V1 G2 is now installed in my ride, anything special  Gen2 and V1Driver? 

V1 driver is the  only app use. I have noticed the bogey shifting around more than with the V1G1, I am guessing due to the G2 increased range and sensitivity?

Looking forward to many more V1Driver miles, especially with my new pony coming next month.

thx rm

**Comment by mswlogo** [comment]
I closed a few old bugs on GitHub and probably got notified. 

Not sure about it jumping around more. Have not been able drive all that much since COVID-19. 

Sounds like V1Driver is working well for you. 

Thanks for responding.

**Comment by rm37** [comment]
hola,

Are you receiving my beta logs?....rm

________________________________

**Comment by mswlogo** [comment]
Are you sending logs from V1Driver or TestFlight?

Last log shown in TestFlight is mid March and I know who it’s from and it’s not you. 

V1Driver logs should have come in but have have not seen any recently from you. 

Also When did you send them.

Also I’m assuming you are on iOS.
